# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='esforco',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='status',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_previsao',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='pre_requisito',
            field=models.ManyToManyField(null=True, related_name='pre_requisitos', to='projeto.Tarefa'),
        ),
    ]
