# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_auto_20170728_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data_previsao',
        ),
    ]
