# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_remove_tarefa_data_previsao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Funcionario'),
        ),
    ]
