# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_tarefa_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='duracao_total',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='horario_de_inicio_atual',
            field=models.DateTimeField(null=True),
        ),
    ]
