# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0005_auto_20170728_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='duracao_total',
            field=models.DurationField(default=0, null=True),
        ),
    ]
