# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0007_auto_20170728_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[(0, 'ABERTA'), (1, 'TRABALHANDO'), (2, 'PAUSADA'), (3, 'CONCLUíDA')], default=0, max_length=1),
        ),
    ]
