# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0008_auto_20170703_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='projeto.Projeto'),
        ),
    ]
