# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0009_comentario_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='projeto.Tarefa'),
        ),
    ]
