# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_auto_20170629_1516'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='checklist',
            table='checklist',
        ),
        migrations.AlterModelTable(
            name='endereco',
            table='endereco',
        ),
        migrations.AlterModelTable(
            name='equipe',
            table='equipe',
        ),
        migrations.AlterModelTable(
            name='funcao',
            table='funcao',
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionario',
        ),
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
        migrations.AlterModelTable(
            name='participacao',
            table='participacao',
        ),
        migrations.AlterModelTable(
            name='projeto',
            table='projeto',
        ),
        migrations.AlterModelTable(
            name='tarefa',
            table='tarefa',
        ),
    ]
