# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_auto_20170629_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participacao',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='projeto.Equipe'),
        ),
    ]
