# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0005_auto_20170702_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='porcentagem_concluida',
        ),
    ]
