# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0011_projeto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Endereco'),
        ),
    ]
