# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0012_auto_20170727_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
        migrations.RemoveField(
            model_name='participacao',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='participacao',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='participacao',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='endereco',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipe',
            name='membros',
            field=models.ManyToManyField(to='projeto.Funcionario'),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Funcao',
        ),
        migrations.DeleteModel(
            name='Participacao',
        ),
        migrations.AddField(
            model_name='comentario',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.Funcionario'),
        ),
    ]
